INSERT INTO GEN.Calendar	(
								[DateInt]	,
								[DateStr]	,
								[Year]		,
								[YrNN]		,
								[YYYYMM]	,
								[Month]		,
								[Day]		,
								[WkDNo]		,
								[workDay]	,
								[WkDName]	,
								[WkDName2]	,
								[WkDName3]	,
								[JulDay]	,
								[Week]		,
								[WkNo]		,
								[Qtr]		,
								[Last]		,
								[LdOfMo]	,
								[LDtOfMo]
							)
SELECT	[DateInt]	,
		[DateStr]	,
		[Year]		,
		[YrNN]		,
		[YYYYMM]	,
		[Month]		,
		[Day]		,
		[WkDNo]		,
		[workDay]	,
		[WkDName]	,
		[WkDName2]	,
		[WkDName3]	,
		[JulDay]	,
		[Week]		,
		[WkNo]		,
		[Qtr]		,
		[Last]		,
		[LdOfMo]	,
		[LDtOfMo]
FROM GEN.GenerateCalendar('2010-01-01', 65536);
GO