CREATE TABLE EXTR.PROCACT
(
	RowID				INT IDENTITY(10000000,1)	NOT NULL,	
	RowEffectiveDate	DATETIME					NOT NULL,
	RowExpiryDate		DATETIME					NOT NULL,
	T$PROC				INT							NOT NULL,
	ACT					INT							NOT NULL,
	POS					INT							NOT NULL,
	ActPos				INT						
	CONSTRAINT pk_EXTR_PROCACT PRIMARY KEY CLUSTERED (RowID)
);
GO