ALTER TABLE GEN.Calendar ADD CONSTRAINT Cal_ix0 UNIQUE NONCLUSTERED([DateStr]);
GO
ALTER TABLE GEN.Calendar ADD CONSTRAINT Cal_ix1 UNIQUE NONCLUSTERED([Year], [Month], [Day]);
GO
ALTER TABLE GEN.Calendar ADD CONSTRAINT Cal_ix2 UNIQUE NONCLUSTERED([YYYYMM], [Day]);
GO