CREATE VIEW ERP.ORDERITEMS
AS
SELECT	 T1.ORDI
		,T1.UDATE
		,T1.ORD
		,T1.ORDNAME
		,T1.ORDSTATUS
		,T1.ORDSTATUSDES
		,T1.CUST
		,T1.PART
		,T1.QUANT
		,T1.DUEDATE
		,T1.ABALANCE
		,T1.T$USER
		,T1.CLOSED
FROM EXTR.ORDERITEMS	AS T1
WHERE T1.RowExpiryDate>GETDATE();
GO
