CREATE VIEW ERP.PART
AS
SELECT	 T1.PART
		,T1.PARTNAME
		,T1.PARTDES
		,T1.EPARTDES
		,T1.TYPE
		,T1.T$PROC
		,T1.PROCNAME
		,T1.FAMILY
		,T1.FAMILYNAME
		,T1.FAMILYDES
		,T1.PARTSTAT
		,T1.STATDES
		,T1.SPEC3
		,T1.SPEC4
		,T1.SPEC8
		,T1.SPEC10
		,T1.SPEC19
FROM EXTR.PART	AS T1
WHERE T1.RowExpiryDate>GETDATE();