CREATE VIEW ERP.SERIAL
AS
SELECT	 T1.SERIAL
		,T1.SERIALNAME
		,T1.SERIALDES
		,T1.SERIALSTATUS
		,T1.SERIALSTATUSDES
		,T1.PSDATE
		,T1.CLOSED
		,T1.PEDATE
		,T1.QUANT
		,T1.CURDATE
		,T1.CLOSEDATE
		,T1.T$USER
FROM EXTR.SERIAL	AS T1
WHERE T1.RowExpiryDate>GETDATE();