CREATE TABLE EXTR.ALINE
(
	 RowID				INT IDENTITY(10000000,1)	NOT NULL	
	,RowEffectiveDate	DATETIME					NOT NULL
	,RowExpiryDate		DATETIME					NOT NULL
	,RowDateTimeStamp	DATETIME					NOT NULL
	,AL					INT							NOT NULL
	,UDATE				INT							NOT NULL
	,FORM				INT							NOT NULL
	,FORMNAME			VARCHAR(16)					
	,SERIAL				INT							NOT NULL
	,PART				INT							NOT NULL
	,ACT				INT							NOT NULL
	,SERCANCEL			CHAR(1)						NOT NULL
	,CURDATE			INT							NOT NULL
	,QUANT				BIGINT						NOT NULL
	,SQUANT				BIGINT						NOT NULL
	,EMPEDATE			INT							
	,EMPSDATE			INT							
	,EMPASPAN			INT							
	,WORKC				INT							NOT NULL
	,SERN				INT	
	 CONSTRAINT pk_EXTR_ALINE PRIMARY KEY CLUSTERED (RowID)						
);
GO


