CREATE TABLE EXTR.SERIAL
(
	RowID				INT IDENTITY(10000000,1)	NOT NULL,	--local field
	RowEffectiveDate	DATETIME					NOT NULL,
	RowExpiryDate		DATETIME					NOT NULL,
	RowDateTimeStamp	DATETIME					NOT NULL,
	SERIAL				INT							NOT NULL,
	UDATE				INT							NOT NULL,
	SERIALNAME			VARCHAR(22)					NOT NULL,
	SERIALDES			VARCHAR(48)					NOT NULL,
	SERIALSTATUS		INT							NOT NULL,	--From SERIALA table
	SERIALSTATUSDES		VARCHAR(12)					NOT NULL,
	PSDATE				INT							NOT NULL,
	PART				INT							NOT NULL,
	CLOSED				CHAR(1)						NOT NULL,
	PEDATE				INT							NOT NULL,
	QUANT				BIGINT						NOT NULL,
	CURDATE				INT							NOT NULL,
	CLOSEDATE			INT							NOT NULL,
	T$USER				INT							NOT NULL,
	CONSTRAINT pk_EXTR_SERIAL PRIMARY KEY CLUSTERED (RowID)
);
GO

CREATE UNIQUE NONCLUSTERED INDEX idx_ERP_UDATE_SERIAL ON EXTR.SERIAL (UDATE,SERIAL) INCLUDE ([RowID],[RowEffectiveDate],[SERIALNAME],[SERIALDES],[SERIALSTATUS],[SERIALSTATUSDES],[PSDATE],[PART],[CLOSED],[PEDATE],[QUANT],[CURDATE],[CLOSEDATE],[T$USER]);
GO
CREATE NONCLUSTERED INDEX idx_ERP_SERIAL_ExpirationDate	ON EXTR.SERIAL (RowExpiryDate) INCLUDE ([RowID],[RowEffectiveDate],[SERIAL],[UDATE],[SERIALNAME],[SERIALDES],[SERIALSTATUS],[SERIALSTATUSDES],[PSDATE],[PART],[CLOSED],[PEDATE],[QUANT],[CURDATE],[CLOSEDATE],[T$USER]);
GO