CREATE NONCLUSTERED INDEX	idx_ERP_ORDERITEMS_ExpiryDate	ON EXTR.ORDERITEMS (RowExpiryDate)
INCLUDE (RowID,RowEffectiveDate,ORDI,UDATE,ORD,ORDSTATUS,ORDSTATUSDES,CUST,PART,QUANT,ABALANCE,DUEDATE,T$USER,CLOSED);
GO