CREATE TABLE EXTR.CUSTOMERS
(
	 RowID				INT IDENTITY(10000000,1)	NOT NULL 	
	,RowEffectiveDate	DATETIME					NOT NULL
	,RowExpiryDate		DATETIME					NOT NULL
	,RowDateTimeStamp	DATETIME					NOT NULL
	,CUST				INT							NOT NULL
	,UDATE				INT							NOT NULL
	,CUSTNAME			VARCHAR(16)					NOT NULL
	,CUSTDES			VARCHAR(48)					NOT NULL
	,CUSTSTAT			INT							NOT NULL
	,STATDES			VARCHAR(12)					NOT NULL
	,COUNTRY			INT	
	,COUNTRYNAME		VARCHAR(18)	
	,CURRENCY			INT							NOT NULL
	,CODE				VARCHAR(3)					NOT NULL	
	,CTYPE				INT							NOT NULL
	,IVTYPE				CHAR(1)						NOT NULL
	,SPEC1				VARCHAR(32)	
	,SPEC2				VARCHAR(32)	
	,SPEC3				VARCHAR(32)
	,SPEC6				VARCHAR(32)
	,SPEC9				VARCHAR(32)	
	CONSTRAINT pk_EXTR_CUSTOMERS PRIMARY KEY CLUSTERED (RowID)	
);

